//
//  SourceSourceLanguage.swift
//  LiveTranslateOffline
//
//  Created by Nirbhay Singh Narang on 1/8/25.
//

import Foundation
struct SourceLanguage: Identifiable, Hashable {
    let id = UUID()
    let code: String
    let name: String
    
    static let supported: [SourceLanguage] = [
        SourceLanguage(code: "af", name: "Afrikaans"),
        SourceLanguage(code: "am", name: "Amharic"),
        SourceLanguage(code: "ar", name: "Arabic"),
        SourceLanguage(code: "as", name: "Assamese"),
        SourceLanguage(code: "az", name: "Azerbaijani"),
        SourceLanguage(code: "be", name: "Belarusian"),
        SourceLanguage(code: "bg", name: "Bulgarian"),
        SourceLanguage(code: "bn", name: "Bengali"),
        SourceLanguage(code: "bs", name: "Bosnian"),
        SourceLanguage(code: "ca", name: "Catalan"),
        SourceLanguage(code: "cs", name: "Czech"),
        SourceLanguage(code: "cy", name: "Welsh"),
        SourceLanguage(code: "da", name: "Danish"),
        SourceLanguage(code: "de", name: "German"),
        SourceLanguage(code: "el", name: "Greek"),
        SourceLanguage(code: "en", name: "English"),
        SourceLanguage(code: "es", name: "Spanish"),
        SourceLanguage(code: "et", name: "Estonian"),
        SourceLanguage(code: "fa", name: "Persian"),
        SourceLanguage(code: "fi", name: "Finnish"),
        SourceLanguage(code: "fr", name: "French"),
        SourceLanguage(code: "ga", name: "Irish"),
        SourceLanguage(code: "gl", name: "Galician"),
        SourceLanguage(code: "gu", name: "Gujarati"),
        SourceLanguage(code: "ha", name: "Hausa"),
        SourceLanguage(code: "he", name: "Hebrew"),
        SourceLanguage(code: "hi", name: "Hindi"),
        SourceLanguage(code: "hr", name: "Croatian"),
        SourceLanguage(code: "hu", name: "Hungarian"),
        SourceLanguage(code: "hy", name: "Armenian"),
        SourceLanguage(code: "id", name: "Indonesian"),
        SourceLanguage(code: "is", name: "Icelandic"),
        SourceLanguage(code: "it", name: "Italian"),
        SourceLanguage(code: "ja", name: "Japanese"),
        SourceLanguage(code: "jw", name: "Javanese"),
        SourceLanguage(code: "ka", name: "Georgian"),
        SourceLanguage(code: "kk", name: "Kazakh"),
        SourceLanguage(code: "km", name: "Khmer"),
        SourceLanguage(code: "kn", name: "Kannada"),
        SourceLanguage(code: "ko", name: "Korean"),
        SourceLanguage(code: "lb", name: "Luxembourgish"),
        SourceLanguage(code: "ln", name: "Lingala"),
        SourceLanguage(code: "lo", name: "Lao"),
        SourceLanguage(code: "lt", name: "Lithuanian"),
        SourceLanguage(code: "lv", name: "Latvian"),
        SourceLanguage(code: "mg", name: "Malagasy"),
        SourceLanguage(code: "mi", name: "Maori"),
        SourceLanguage(code: "mk", name: "Macedonian"),
        SourceLanguage(code: "ml", name: "Malayalam"),
        SourceLanguage(code: "mn", name: "Mongolian"),
        SourceLanguage(code: "mr", name: "Marathi"),
        SourceLanguage(code: "ms", name: "Malay"),
        SourceLanguage(code: "mt", name: "Maltese"),
        SourceLanguage(code: "my", name: "Myanmar"),
        SourceLanguage(code: "ne", name: "Nepali"),
        SourceLanguage(code: "nl", name: "Dutch"),
        SourceLanguage(code: "no", name: "Norwegian"),
        SourceLanguage(code: "or", name: "Odia"),
        SourceLanguage(code: "pa", name: "Punjabi"),
        SourceLanguage(code: "pl", name: "Polish"),
        SourceLanguage(code: "ps", name: "Pashto"),
        SourceLanguage(code: "pt", name: "Portuguese"),
        SourceLanguage(code: "ro", name: "Romanian"),
        SourceLanguage(code: "ru", name: "Russian"),
        SourceLanguage(code: "sa", name: "Sanskrit"),
        SourceLanguage(code: "sd", name: "Sindhi"),
        SourceLanguage(code: "si", name: "Sinhala"),
        SourceLanguage(code: "sk", name: "Slovak"),
        SourceLanguage(code: "sl", name: "Slovenian"),
        SourceLanguage(code: "sn", name: "Shona"),
        SourceLanguage(code: "so", name: "Somali"),
        SourceLanguage(code: "sq", name: "Albanian"),
        SourceLanguage(code: "sr", name: "Serbian"),
        SourceLanguage(code: "su", name: "Sundanese"),
        SourceLanguage(code: "sv", name: "Swedish"),
        SourceLanguage(code: "sw", name: "Swahili"),
        SourceLanguage(code: "ta", name: "Tamil"),
        SourceLanguage(code: "te", name: "Telugu"),
        SourceLanguage(code: "tg", name: "Tajik"),
        SourceLanguage(code: "th", name: "Thai"),
        SourceLanguage(code: "tk", name: "Turkmen"),
        SourceLanguage(code: "tl", name: "Tagalog"),
        SourceLanguage(code: "tr", name: "Turkish"),
        SourceLanguage(code: "tt", name: "Tatar"),
        SourceLanguage(code: "uk", name: "Ukrainian"),
        SourceLanguage(code: "ur", name: "Urdu"),
        SourceLanguage(code: "uz", name: "Uzbek"),
        SourceLanguage(code: "vi", name: "Vietnamese"),
        SourceLanguage(code: "yi", name: "Yiddish"),
        SourceLanguage(code: "yo", name: "Yoruba"),
        SourceLanguage(code: "zh", name: "Chinese")
    ]
}
